### ISSUE TITLE
No time_series_container in VariableReserve "Flex_Up" and "Flex_Down" for "RTS_GMLC_RT_sys"

### ISSUE THREAD

**Issue by alefcastelli** [NREL-Sienna/PowerSystemCaseBuilder.jl#68]
Missing time series for the `VariableReserve` "Flex_Up" and "Flex_Down" (example below).
These are present for the same `VariableReserve` in the `RTS_GMLC_DA_sys` system. Therefore, when trying to run a simulation in PowerSimulations with `RTS_GMLC_RT_sys` and `RTS_GMLC_RT_sys`, the following error happens:

`┌ Error: Simulation build failed
│   exception =
│    ArgumentError: time_series InfrastructureSystems.TimeSeriesKey(InfrastructureSystems.DeterministicMetadata, "requirement") is not stored`

Example:
`Flex_Down (VariableReserve{ReserveDown}):
   name: Flex_Down
   available: true
   time_frame: 1200.0
   requirement: 0.98
   sustained_time: 3600.0
   max_output_fraction: 1.0
   max_participation_factor: 1.0
   deployed_fraction: 0.0
   ext: Dict{String, Any}()
   time_series_container: <--- here is the problem!
   InfrastructureSystems.SystemUnitsSettings:
      base_value: 100.0
      unit_system: UnitSystem.SYSTEM_BASE = 0`

**Comment by jd-lara** [comment]
Closed as this is an issue in the raw data
